//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResources.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HumanResourcesEntities : DbContext
    {
        public HumanResourcesEntities()
            : base("name=HumanResourcesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int PR_AdminLogin(string username, string password, ObjectParameter responseMessage, ObjectParameter idAdmin)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_AdminLogin", usernameParameter, passwordParameter, responseMessage, idAdmin);
        }
    
        public virtual int PR_CrateEmployee(Nullable<decimal> identification, string name, string lastname, string email, string phone, string gender, string maritalState, string adress, Nullable<System.DateTime> birthdate, ObjectParameter responseMessage)
        {
            var identificationParameter = identification.HasValue ?
                new ObjectParameter("Identification", identification) :
                new ObjectParameter("Identification", typeof(decimal));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("Lastname", lastname) :
                new ObjectParameter("Lastname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var maritalStateParameter = maritalState != null ?
                new ObjectParameter("MaritalState", maritalState) :
                new ObjectParameter("MaritalState", typeof(string));
    
            var adressParameter = adress != null ?
                new ObjectParameter("Adress", adress) :
                new ObjectParameter("Adress", typeof(string));
    
            var birthdateParameter = birthdate.HasValue ?
                new ObjectParameter("Birthdate", birthdate) :
                new ObjectParameter("Birthdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CrateEmployee", identificationParameter, nameParameter, lastnameParameter, emailParameter, phoneParameter, genderParameter, maritalStateParameter, adressParameter, birthdateParameter, responseMessage);
        }
    
        public virtual int PR_CreateAdmin(string userName, string password, ObjectParameter responseMessage)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CreateAdmin", userNameParameter, passwordParameter, responseMessage);
        }
    
        public virtual ObjectResult<PR_ViewEmployees_Result> PR_ViewEmployees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_ViewEmployees_Result>("PR_ViewEmployees");
        }
    }
}
